name: note build
# 触发workflow的条件
on:
  push:
    # 只有master分支发生push事件时，才会触发workflow
    branches: [master]
  pull_request:
    branches: [master]

env:
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.REMOTE_HOST }} # 服务器IP地址
  USER_NAME: ${{ secrets.REMOTE_USER }} # 服务器用户名
  cache-name: note

# jobs表示执行的一项或多项任务
jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: v18.17.0

      # 备份目标文件夹（如果存在的话）
      - name: Backup dist folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script:
            IF EXIST "C:\Users\Administrator\Desktop\nginx-1.24.0\nginx-1.24.0\dist" (
            move "C:\Users\Administrator\Desktop\nginx-1.24.0\nginx-1.24.0\dist" "C:\Users\Administrator\Desktop\nginx-1.24.0\nginx-1.24.0\backup%DATE:~0,4%%DATE:~5,2%%DATE:~8,2%%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%"
            )

      #缓存依赖
      - name: Cache nodemodules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # 需要缓存的文件的路径
          path: ./node_modules
          # 对缓存的文件指定的唯一标识
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
          # 用于没有再找目标key的缓存的backup选项
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 装依赖
      - name: Install
        run: yarn

      # 打包
      - name: Build
        run: yarn build


        # 复制文件到服务器
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          #需要部署的文件地址 本地dist目录下的所有文件
          source: dist/*
          # SSH address  服务器地址
          host: ${{ secrets.REMOTE_HOST }}
          # Remote dir path  服务器下部署文件存放路径
          target: C:\Users\Administrator\Desktop\nginx-1.24.0\nginx-1.24.0/
          # SSH Port  服务器端口
          port: 22
          # SSH User name   用户名
          username: ${{ secrets.REMOTE_USER }}
          # SSH User password  用户密码
          password: ${{ secrets.PASSWORD }}
          # key  密匙
          key: ${{ secrets.SERVER_PRIVATE_KEY }}

      # 备份目标文件夹（如果存在的话）
#      - name: Backup dist folder
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          port: 22
#          username: ${{ secrets.REMOTE_USER }}
#          password: ${{ secrets.PASSWORD }}
#          key: ${{ secrets.SERVER_PRIVATE_KEY }}
#          script:
#            move "C:\Users\Administrator\Desktop\nginx-1.24.0\nginx-1.24.0\dist" "C:\Users\Administrator\Desktop\nginx-1.24.0\nginx-1.24.0\backup"
